### Creates a new entity person
PUT http://localhost:8080/people
Authorization: Bearer xyz
Content-Type: application/json

{
  "firstname": "tomas",
  "lastname": "kozak",
  "email": "email@talko.cz",
  "born": "1991/04/21",
  "height": 187,
  "family": {
    "daddy": "tata",
    "mommy": "mama"
  },
  "tags": [
    {
      "name": "fv_color",
      "value": "green"
    }
  ],
  "nums": [
    6,
    7,
    8
  ]
}

### Get list of all people
GET http://localhost:8080/people
Authorization: Bearer xyz

### Get payload data of entity by ID
GET http://localhost:8080/people/6a10dd3f-b291-4c03-7a05-7195b7a26ffe
Authorization: Bearer xyz

### Delete person from the list
DELETE http://localhost:8080/people/f1bc757c-8e3a-436d-6b50-c37ee8d0d65f
Authorization: Bearer xyz

### Creates a new entity dog
PUT http://localhost:8080/dogs
Content-Type: application/json

{
  "name": "cumacek",
  "cuteness": 7
}

### Get list of all dogs
GET http://localhost:8080/dogs

### Get payload data of entity by ID
GET http://localhost:8080/dogs/63c85fae-251f-45ab-7ac6-e9a6ab26ecd0

### Delete person from the list
DELETE http://localhost:8080/dogs/37e5604a-b38d-45cf-5692-fe0c54253e63

### Get Prometheus metrics
GET http://localhost:8080/metrics

### Get Homepage data
GET http://localhost:8080

### Set logging level Homepage data
POST http://localhost:8080/log_level
Authorization: Bearer llkey
Content-Type: application/json

{
  "level": "fatal"
}
